{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": 1,
 "templating": {
  "list": [
   {
    "name": "accountID",
    "label": "Account ID",
    "query": "label_values(Total_Account_Cost99, account_id)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(Total_Account_Cost99{account_id=\"${accountID}\"}, region)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(Total_Account_Cost99{account_id=\"${accountID}\", region=\"${region}\"}, project)"
   },
   {
    "name": "month",
    "label": "Month",
    "query": "label_values(Total_Account_Cost99{account_id=\"${accountID}\", region=\"${region}\", project=\"${project}\"}, month)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tracking Total Costs Across Multiple Accounts",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(month) (Total_Account_Cost{month=~\"$Month\", job=\"Total_Account_Cost\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Account Account Cost for last 3 months",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Total_Account_Cost{job=\"Total_Account_Cost\", account_id=\"$Account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project Spend Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Project_Spend_Cost{job=\"Project-Spend-Cost\", project_spend_project=\"$Project\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 most expensive services ",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "Expensive_Services_Detail{job=\"Most_Expensive_Services\", region=\"$region\", account=\"$Account\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}